-- Instagram project: public.reels (run in Instagram Supabase SQL Editor)
create table public.reels (
  id text not null default (gen_random_uuid())::text,
  shortcode text null,
  ownerusername text null,
  ownerfullname text null,
  ownerid text null,
  caption text null,
  likescount bigint null,
  commentscount text null,
  videoviewcount bigint null,
  videoplaycount bigint null,
  videowatchcount text null,
  repostcount text null,
  payout text null,
  sentcount text null,
  sharecount text null,
  locationname text null,
  timestamp text null,
  takenat text null,
  lastupdatedat text null,
  publishedtime text null,
  displayurl text null,
  videourl text null,
  thumbnailurl text null,
  audioname text null,
  audiourl text null,
  producttype text null,
  url text null,
  permalink text null,
  inputurl text null,
  created_at timestamp with time zone null,
  updated_at timestamp with time zone null,
  created_by_user_id text null,
  created_by_email text null,
  created_by_name text null,
  is_archived boolean null,
  archive_reason text null,
  archived_at text null,
  refresh_failed boolean null,
  refresh_failed_reason text null,
  video_duration integer null,
  language text null default 'hinglish'::text,
  last_refreshed_at timestamp without time zone null,
  next_refresh_at timestamp without time zone null,
  refresh_priority smallint null,
  constraint reels_pkey primary key (id),
  constraint reels_shortcode_unique unique (shortcode)
) tablespace pg_default;
